### ISSUE TITLE
Two small issues

### ISSUE THREAD

**Issue by markc** [icitry/BashTube#1]
Thank you for this amazing project. So much to learn from.

a) BashTube/src/rest/http/http_orchestrator.sh needs to be chmod +x

b) Getting this error when trying to upload a video using Firefox...

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8080/upload. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 201.

**Comment by icitry** [comment]
Hi, I'm really happy to hear that!

Now, for the issues:

1.  A "Setting up" section has been added to the README, as the project is simple enough that a installation script is not necessary.
2. I could not repro your issue on the latest Firefox build, but have added the CORS header described by your issue. If the problem persists, let me know, or feel free to submit a PR.

**Comment by markc** [comment]
Not so fast :-)

It seems I can now upload a small mp4, it's just that without any feedback I accidentally uploaded some more copies. However, when trying to refresh the page, I get the attached similar error.

Another docu point is that it took me quite a few attempts to figure out which script to run, and that it's necessary to cd into src/app first before running a bash main.sh.

![20241005_090539](https://github.com/user-attachments/assets/5d5e0a57-3524-499d-9b6a-7e2f3166d789)

**Comment by icitry** [comment]
Hi again! :)

1. As you pointed out, I added a new part to the "Setting up" section for running the actual app.
2. Also added a global preflight requests handler that should theoretically handle your error case, although considering how complex/varied browser behavior is, it may very well not be a end-all solution - after all, this is really just a simple Bash app.

**Comment by markc** [comment]
Getting further along but getting the below. I was also missing the "bc" command, so maybe a setup script might be a good idea to check that all binary dependencies exist, and a chmod along the way.
```
[05/10/24 22:10:27][DEBUG][HTTP]: GET / HTTP/1.1 200
[05/10/24 22:10:27][DEBUG][HTTP]: GET /static/bashtube_logo.png/ HTTP/1.1 200
[05/10/24 22:10:27][DEBUG][HTTP]: GET /storage/user_icon.jpg/ HTTP/1.1 200
[05/10/24 22:11:23][DEBUG][HTTP]: POST /upload/ HTTP/1.1 201
[05/10/24 22:11:39][DEBUG][HTTP]: POST /videos/ HTTP/1.1 400
[05/10/24 22:11:52][DEBUG][HTTP]: GET / HTTP/1.1 200
[05/10/24 22:11:52][DEBUG][HTTP]: GET /static/bashtube_logo.png/ HTTP/1.1 200
[05/10/24 22:11:52][DEBUG][HTTP]: GET /storage/0/ HTTP/1.1 404
[05/10/24 22:11:52][DEBUG][HTTP]: GET /storage/user_icon.jpg/ HTTP/1.1 200
[05/10/24 22:11:52][DEBUG][HTTP]: GET /storage/video_upload_1ca7b7e9-06d5-4487-9d6b-6c39dffac767.mp4/ HTTP/1.1 200
Error: in prepare, no such column: user_icon.jpg
  SELECT * FROM videos WHERE id = user_icon.jpg;
                    error here ---^
[05/10/24 22:12:08][DEBUG][HTTP]: GET /videos/user_icon.jpg/ HTTP/1.1 404
```

**Comment by icitry** [comment]
The bc command is most definitely a sub-requirement to the 3 major dependencies that I will be adding to the README (thanks for pointing that out).
From the error log it seems you are trying to access /videos/user_icon.jpg/ which is correctly returning 404 - the error doesn't interrupt the flow of the app. Is something related to that the problem? You may want to clear your database if some entries are malformatted (which may be possible if your first attempts at uploading videos were only partial).
